-- scheduled queries running on raw tables & their freq

-- SELECT scheduled_query_name, refresh_schedule, job_id from t1

-- SELECT job_id, CONCAT(referenced_tables.dataset_id, ".", referenced_tables.table_id) table_id, SUM(total_slot_ms)/(1000*24*30)


SELECT  `scheduled_query_name` AS `scheduled_query_name`,
       `refresh_schedule` AS `refresh_schedule`,
       sum(`count_jobs_per_day`) AS `runs_per_day`,
       sum(`slot_day`) AS `SUM_slot_day`
FROM
  (SELECT DISTINCT tt1.*,
                  --  tt2.team_name,
                  --  tt2.pod_name,
                  -- CONCAT('https://console.cloud.google.com/bigquery/scheduled-queries/locations/us/configs/', transferConfigID, '/runs?project=', project_id) scheduled_query_link
   from
     (WITH t1 AS
        (SELECT distinct date(creation_time, "Asia/Kolkata") dt,
                          i.project_id,
                        --  user_email,
                         job_id,
                         total_slot_ms,
                        --  TIMESTAMP_DIFF(end_time, start_time, second) runtime
         from `region-us`.INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION i, UNNEST(referenced_tables)
         WHERE date(creation_time, "Asia/Kolkata") = CURRENT_DATE("Asia/Kolkata") - 2
           AND job_id LIKE "%scheduled%"
           AND (statement_type IS NULL
                OR UPPER(statement_type) NOT IN ("SCRIPT")) ),
           t2 AS
        (SELECT distinct owner_email_id,
                         scheduled_query_name,
                         transfer_config_id,
                         refresh_schedule
         FROM maximal-furnace-783.data_platform_temp1.scheduled_queries_meta
         WHERE date(ingest_time, "Asia/Kolkata") = CURRENT_DATE("Asia/Kolkata") - 2
           AND disabled IS FALSE),
           t3 AS
        (SELECT distinct OwnerEmail,
                         TransferConfigID,
                         BQJobID
         from maximal-furnace-783.data_platform_temp1.scheduled_query_runs),
           t4 AS
        (SELECT distinct t2.owner_email_id,
                         t2.scheduled_query_name,
                         t2.refresh_schedule,
                         t3.transferConfigID,
                         t3.BQJobID
         from t2
         INNER JOIN t3 ON (t2.transfer_config_id) = (t3.transferConfigID)) SELECT DISTINCT t1.dt,
                                                                                   
                                                                                           t4.scheduled_query_name,
                                                                                           t4.refresh_schedule,
                                                                                           t4.transferConfigID,
                                                                                           COUNT(distinct job_id) count_jobs_per_day,
                                                                                           SUM(t1.total_slot_ms)/(1000*3600*24) slot_day
      from t1
      INNER JOIN t4 ON (t1.job_id) = (t4.BQJobID)
      group by all) tt1
   order by 1 ASC) AS `virtual_table`
WHERE scheduled_query_name IN 
('90_days_vp_data',
'acquisition_campaignwise_avgcpi',
'acquisition_campaignwise_view',
'acquisition_cohort_live_ranker_notif',
'acquisition_main_cohort_view',
'acquisition_main_cohort_view_organic',
'acquisition_main_cohort_view_organic_moj',
'acquisition_main_cohort_view_paid_moj',
'acquisition_main_view',
'acquisition_main_view_updated',
'acquisition_spend_0to180_funnel',
'acquisition_spend_0to180_funnel_updated',
'Active and have mints',
'Active not used Spot',
'active_frnd_hosts',
'Active_frnd_hosts_F2P',
'Active_frnd_Latest_Free_to_paid',
'active_frnd_paid_calls',
'ad_imps on MOJ',
'ad_view attributes user coverage',
'ad_view_post',
'Admissed_Combined',
'Ads Transaction share',
'ads_analytics_aggp',
'ads_revenue',
'ADSDAU on MJ',
'ADSDAU on SC',
'adsSepnds_v_walletDeductions',
'Advertiser_Diveristy',
'adview_adsuuid_level_main',
'adview_trainingdata_clicks',
'adview_trainingdata_imps',
'adview_trainingdata_installs',
'adview_user',
'adview_userlevel_view',
'adview_userlevel_view_moj',
'adview_userlevel_view_moj_main',
'agc_safeguard_scsupply',
'Agency - earning to earning Ret',
'Agency_active_to_active_Ret',
'agency_chatroom_mapping',
'agency_creator_min_views_sa',
'agency_deeper_comparison',
'Agency_Old_New_Payout_Eligible',
'agency_ugc_cpp_daily_active_host',
'All_Chatroom_VG_Hosts',
'All_Query_TR_Moj_Live',
'APK vs PS Dashboard',
'ar_analytics_followers',
'ar_analytics_followers_daily_update',
'astra_ads_clicked',
'astro_attendee_notif',
'astro_automated_notif_issued',
'astro_BE_automated_notification_new',
'astro_feed_fz_grading_new9',
'astro_funnel_and_call_data_today',
'astro_gold_host_availabilty_5_min_buckets_7_days',
'astro_gold_supply',
'astro_host_availabilty_5_min_buckets',
'astro_non_recharger_hindi_user',
'Audience_segment_language_MJ',
'Audience_segment_language_unified',
'Audience_Segments_Language_SC',
'Audios_metadata_correction',
'Balancer_Live_injection',
'banner_user_cohort_1',
'banner_user_cohort_11',
'banner_user_cohort_13',
'banner_user_cohort_4',
'banner_user_cohort_5',
'banner_user_cohort_6',
'banner_user_cohort_7',
'banner_user_cohort_8',
'banner_user_cohort_9',
'battle match logic query',
'battle_gifters_supply_side',
'battle_notifications',
'BE_Networks_latest',
'BE_Revenue_Metrics_New',
'BLS Cohort',
'BLS_Dashboard_Campaigns',
'bls_posts',
'blue_analytics_average_base_data',
'blue_analytics_base_table_data',
'blue_analytics_base_table_data_mcl',
'blue_analytics_base_table_data_spot',
'blue_analytics_personalised_base_data',
'BM_wise_camps',
'boost_leaderboard',
'boosted_views_older_version_exp',
'boosted_views_share',
'Brand',
'Brand DRR MJ',
'Brand DRR SC',
'Brand Roadblock',
'Branded Share Posts',
'branded_hashtag_views',
'branded_influencer_campaign_data',
'branded_influencer_likes',
'branded_influencer_pinned_posts',
'branded_influencer_views',
'branded_lens_audio_posts',
'branded_posts_p_views',
'Campaign Debugging V2',
'campaign_crud_dailylevel',
'campaign_performance',
'Cash_Out_Nudge_CTA1',
'category_q3_okr_sc_live',
'category_wise_cr_users',
'category_wise_non_cr_users',
'cb_punish_mode_mapping',
'cb_requests_when_host_was_busy',
'cb_suggestions_opponent_table',
'cb_suggestions_score_history_table',
'cb_suggestions_score_table',
'Central Admissed',
'cg_distribution_friends_feed_v2',
'challenge_pinning_dump v1.2',
'chartroom_install_table',
'chatroom_funnel',
'chatroom_gifter_x_host_table',
'chatroom_ho_to_arpu_funnel',
'chatroom_level_Data',
'chatroom_level_eng_score_final',
'chatroom_scores_for_ranker',
'chatrooms_d1_pu_rolling_ret',
'chatrooms_d3_pu_rolling_ret',
'chatrooms_d30_pu_rolling_ret',
'chatrooms_first_users',
'cid_level_daily_data',
'cid_level_data_ugc_cpp',
'classified_lang_dau',
'classified_posts_sessions',
'CM Video Play 11PM Daily Job',
'coin_bag_users_event',
'Coin_Gifters_Per_Creator',
'consultation_host_label',
'consultation_host_label_benchmark',
'consultation_host_label_data',
'consultation_trending_feed_users',
'content_slot_exp_retention_v2',
'content_slot_exp_retention_v3',
'content_slot_exp_retention_v3_child',
'content_slot_exp_timespent',
'content_slot_exp_timespent_v2',
'content_slot_exp_timespent_v3',
'content_slot_inventory',
'content_slot_inventory_v2',
'content_slot_old_version_exp_inventory',
'content_slot_vp_data',
'cpp_sc_live_basic_metrics',
'cpp_sc_live_basic_metrics_weekly',
'CR_FZ_overlap',
'cr_gifters_cohort',
'cr_notif_cleanedup_users',
'create or replace table  `sc-bigquery-product-analyst.divyanshu_gera.direct_to_chatroom_exclusions` as',
'Create or Replace Table `sc-bigquery-product-analyst.Rohan_Sakeri.fz_aka_vibe_initial_consultation_dt` As',
'Creator Activity Weekly kartik',
'creator_affinity_notif_variant_assignment',
'creator_aggregate_details',
'creator_aggregate_details_daily',
'creator_battle_moj_live_daily_dump',
'creator_follow_notif_3hr_source -scheduled',
'creator_grading_daily_aggregate',
'creator_led_notifications',
'creator_level_cold_start_sa',
'creator_marketplace_age_followers',
'creator_score_onboarding_l0',
'creator_score_percentile',
'Creator_Type_FZ_Final',
'creators_redistribution_master_list',
'crj_asj_conn',
'crj_eng_conn',
'CTR RCE summary',
'cumulative_followers_count_base_query',
'd123personalisation_pre_genre',
'd123userlevelpersonalisation',
'daily nri domestic gmv',
'daily_asj_connections_v2',
'daily_comment_connections',
'daily_count_top_funnel_moj_live',
'Daily_Creator_Active',
'Daily_Creator_earnings',
'daily_dau',
'daily_fz_bottom_nav_metrics',
'daily_fz_ct_metrics',
'daily_fz_dau (IM)',
'daily_fz_gmv (IM)',
'daily_fz_gold_hosts',
'daily_fz_newold_metrics',
'daily_fz_pickuprate',
'daily_fz_retention_metrics',
'daily_fz_retention_metrics_cf_header',
'daily_fz_widget_metrics',
'daily_gifting_1_connections',
'daily_gifting_100_connections',
'daily_gifting_100_connections_v2',
'daily_gifting_1000_connections',
'daily_gifting_1000_connections_v2',
'daily_gifting_20_connections',
'daily_gifting_20_connections_v2',
'daily_gifting_500_connections',
'daily_gifting_500_connections_v2',
'daily_gifting_recharge_gmv',
'daily_gmv_earned',
'daily_host_level_data',
'daily_host_level_fz_data',
'Daily_Marketing_PU_data',
'daily_moj_live_gmv_recharge_gift_he',
'daily_mpu_logs_sa',
'daily_paid_gifters',
'daily_report_OUeyE2db4q',
'daily_room_joiners',
'date_level_gifter_data',
'Day_wise_camps',
'Default ArsTimeOut Overall',
'Default_timeout_trendlines',
'DefaultArsTimeoutNetwork',
'DefaultArsTimout',
'Delist_non_clickers',
'Delist_non_clickers_Plus_Aman\'s_data',
'delisting_non_clickers',
'devotion_bucket_explored',
'DRR SC ads impressions',
'DRR SC impressions',
'DRR_Dashbaord_MJ',
'DRR_dashbaord_SC',
'ds_notif_cg_popular_posts_v3',
'DSA Loadtime',
'DSA Product Query',
'DSA_events_schedule',
'dynamic tcpa sanity dashboard',
'dynamic threshold calculator for magic click',
'Dynamic_Appwall_i2i',
'eng_date_referrer_meta',
'engagement_friends_feed_v2',
'engagement_score_new_recharger_new',
'entry_effect_affinity',
'Eppo Ad Units Inclusion Daily Check',
'explore_bounce_rate',
'explore_conusmption_metrics_dashboard',
'feed_fetch_funnel_friends_feed_v2',
'Feedback_Loop_DAU',
'Feedback_Loop_Gifters',
'Final_New_Widget_Pinning',
'flashsale_temp',
'floating_widget_data',
'floating_widget_forecast',
'followers_count_base_query_rolling',
'Followers_daily_aggregate',
'followers_triggers',
'free_coins_past_15_days_avg_std_values',
'friend_suggestion_v2',
'friend_zone_host_grading_12',
'friend_zone_host_grading_3',
'friendzone_blacklisting_app_installed',
'FRND_hosts_f2P_d1',
'FRND_hosts_F2P_d3',
'FRND_Hosts_F2P_d7',
'frnd_hosts_free_calls',
'FRND_Hosts_Free_to_paid',
'FRND_hosts_P2P_latest_D1',
'FRND_hosts_P2P_latest_D3',
'FRND_hosts_P2P_latest_D7',
'frnd_hosts_paid_calls',
'FRND_qactive_hosts_paid_calls',
'FrontEnd_objects',
'funnel_international_users',
'fz_call_data',
'FZ_Clickers_Lifetime',
'FZ_target_CR_ids',
'FZ_user_dump',
'GAM_ad_requests',
'gamezop_agg',
'gamification_current_badge_backfill',
'gamification_current_badge_update',
'gamification_fake_likes_v2',
'gamification_levels_percent_creators_opening_TK_daily',
'gamification_levels_TK_openers_daily',
'gamification_real_likes_v2',
'gamification_reduced_plikes',
'gamification_TK_openers_creation_days_per_creator',
'gamification_TK_openers_D1_D7_retention',
'gamification_TK_openers_daily',
'gamification_TK_openers_ppc',
'gamification_TK_openers_weekly',
'gamification_TK_openers_widget_clickers_weekly',
'gamification_vv_final_backfill',
'gamification_vv_final_update_venkat',
'gamification_vv_finalposts_venkat',
'gamification_vv_pviews_venkat',
'gcj_30D',
'gcj_60D',
'gcj_90D',
'genre_top_video_posts_last_14_days',
'gift_level_data_mtd_values',
'gifter_gender_to_host_gender_gmv',
'gifter_rfm_version1',
'gifting_rec_agg_w_new',
'global_levels_cheers_burn_break_up_sa',
'google_indexing',
'grade_wise_creators_daily_base_table_rolling',
'greedy_monetory_data',
'greedy_player_numbers',
'greedy_winner_loosers',
'HardikGoyal_scBlue_dailyUserActivityFunnel',
'heart_breakup_search',
'high spot select failed',
'HIGHEST_BATTLE_COINS',
'HIGHEST_BATTLE_COINS_AG_HOST',
'HIGHEST_BATTLE_COINS_GIFTER',
'HIGHEST_CHATROOM_LEVEL',
'HIGHEST_CHATROOM_LEVEL_AG',
'HIGHEST_CHATROOM_LEVEL_UGC',
'HIGHEST_MONTHLY_GIFTING_AG_HOST',
'HIGHEST_MONTHLY_GIFTING_GIFTER',
'HIGHEST_MONTHLY_GIFTING_UGC_HOST',
'HIGHEST_SINGLE_DAY_GIFTING_GIFTER',
'HIGHEST_SINGLE_DAY_GIFTING_HOST',
'HIGHEST_USER_LEVEL',
'home_open_50_days',
'home_open_funnel_explore',
'host_active_to_active_d1_ret',
'host_earning_to_earning_d1_ret',
'host_led_games_okr',
'host_level_data_mtd_values',
'Host_Sessions_Per_Host_Daily',
'host_wise_eng_score',
'hourly_fz_dau',
'hourly_fz_gold_hosts',
'htc_daily_data',
'htcOrganicBoostedPosts',
'i2i rce summary',
'ia_daily_data',
'ia_sparkad_follow',
'IKEA cohort',
'Ikea_ladering_staging_v1',
'Ikea_ladering_V1',
'Ikea_ladering_V2',
'Imps on MOJ',
'InActive and have mints',
'infrequent_pus_offers',
'Insert Brands Dashboard rev',
'Insert_bls_temp1',
'insert_bls_temp2',
'Install_Dashboard',
'Install_Dashboard_CampaignWise',
'Install_Dashboard_Overall',
'Instream_data',
'interaction_score',
'International_FZ_gifters_overall_level',
'International_FZ_users_language_level',
'International_FZ_users_overall_level',
'job_business_search',
'job_posts_views_clicks_creation_date',
'jyotish_bucket_explored',
'kapil_creative_refreshment_dashboard',
'Kapil_supply_dashboard_data',
'kartikt_UGT_For_Taxonomy',
'Key Value Pair GAM Experiments',
'L2_Filtered_Posts_v2',
'L30D_SC_Interactors',
'label_shown_friends_feed_v2',
'lang_level_dashboard',
'langgenre',
'language_fz_daily_user',
'Last_month_reward_gems',
'Last_month_reward_gems_New',
'LCB_CPC_view',
'ledger_daily_im_pu_gmv_new_old',
'ledger_daily_pu_gmv_new_old',
'ledger_daily_pu_gmv_new_old_v2',
'lens_audio_pair',
'likes_shares_followers_till_yesterday',
'Live Creator Affinity Notifications Query',
'live_2MAU_sa',
'live_creator_activation_sa',
'live_daily_users_im',
'live_daily_users_im_lang',
'live_first_notifications',
'live_gifting_auto_positioning_base_sa',
'live_gifting_auto_positioning_cohorts_sa',
'live_gifting_auto_positioning_s2_sa',
'live_gifting_auto_positioning_s3_sa',
'live_gifting_auto_positioning_s4_sa',
'live_gifting_auto_positioning_s5_sa',
'live_monetary_rewards_agg_sa',
'Live_New_PU_ID_wise',
'live_system_messages_final_cohort_v1',
'LiveExp_joindata_ram',
'livestream_agg',
'livestream_creator_mapping',
'livestream_creator_score_sa',
'livestream_data_agg',
'livestream_highlight_creator_affinity_score_sa',
'loan_funnel_3cr',
'loan_funnel_3cr_L7D',
'loan_notification',
'love_marriage_search',
'ludorandom_agg',
'ludorandom_agg_retention',
'main_todays_view',
'main_view',
'main_view_install_2d',
'main_view_purchase_2d_main',
'make_friends_chatroom_created',
'MAU_DM_Control',
'MaxPositionTemp',
'mcr_monetised_creator_L180D',
'mediaplanner_htc_ia_videoplay_v2',
'meta_VTC',
'MFC_application_action_record',
'mfc_live_10k_gmv_month',
'mfc_live_ft_10k_gmv_month',
'MJ ads CPI based DRR report',
'MJ BM Impressions',
'MJ BM wise DRR',
'MJ CPI Based DRR Report',
'MJ Dynamic Bidder Direct',
'MJ imp clk cpm',
'MJ Max Position',
'MJ_AdNetwork_CTR',
'MJ_CA_l0_demo',
'MJ_CA_l0_l1_demo',
'MJ_CA_l0_l1_state',
'MJ_CA_l0_l1_tier',
'MJ_CA_l0_lang',
'MJ_CA_l0_State',
'MJ_CA_l0_tier',
'MJ_CA_lo_l1_lang',
'MJ_homeopened_traffic',
'MJ_Last_10days_CTR',
'moj blue final',
'Moj budgetAB daily',
'MOJ frontend drop (ARS and After mediation)',
'MOJ Frontend objects summary',
'MOJ Lite Admissed',
'MOJ TT admissed',
'MOJ TT LITE Imps trends',
'Moj User Static Dimensions Cube - Daily Overwrite Refresh',
'MOJ_admissed',
'moj_analytics_user_deactivation',
'moj_attribution_views',
'moj_blue_l60',
'moj_blue_status',
'moj_cohortized_spinwheel_sa',
'moj_creator_analytics_creator_hourly_eng - scheduled oct20',
'moj_creator_analytics_creator_top_posts',
'moj_creator_analytics_hourly_creator_discarded_2',
'moj_creator_analytics_hourly_post_discarded_2',
'moj_creator_analytics_post_hourly_eng - scheduled oct 20',
'MOJ_DAU_schedule',
'moj_hungry_game_social_proof_sa',
'moj_lite_mau_sa',
'Moj_lite_SV_feed_data_prod_sa',
'moj_live_and_gifter_dau_bucket',
'moj_live_creator_earning_group',
'moj_live_creator_earning_group_dayofmonth',
'moj_live_creator_earning_group_dod',
'moj_live_creator_earning_group_mom',
'moj_live_creator_earning_group_MTD',
'moj_live_creators_growth_sa',
'moj_live_livestreamfeature_comment_match_perc',
'moj_live_livestreamfeature_dt_liker_match_perc',
'moj_live_livestreamfeature_like_match_perc',
'moj_live_livestreamfeature_share_match_perc',
'moj_live_liveUser_cheersSpent_match_perc',
'moj_live_liveUser_comments_match_perc',
'moj_live_liveUser_distinctLikes_match_perc',
'moj_live_liveUser_distinctSharedHosts_match_perc',
'moj_live_liveUser_distinctSharedLivestreams_match_perc',
'moj_live_liveUser_likeCount_match_perc',
'moj_live_liveUser_shares_match_perc',
'moj_live_min_view_calc',
'moj_live_notification_affinity',
'moj_live_recharge',
'moj_live_referral_dashboard_base',
'moj_livestream_daily_gifter_ge',
'moj_livestream_daily_gifter_grouping_count_ge',
'moj_livestream_daily_gifter_retention_rates_ge',
'moj_livestream_moderation_reports_journey',
'moj_livestream_moderation_reports_journey_staging',
'MOJ_MAU_Schedule',
'Moj_new_uploads_prod_exp',
'moj_non_pii_user_table',
'moj_popular_fallback',
'Moj_search_score',
'moj_slot_machine_social_proof_sa',
'moj_spot_daily_fulfillment_rate_base_data_support_team',
'moj_spot_daily_fulfillment_rate_rolling',
'moj_spot_daily_fulfillment_rate_video_play_data_1stMar_rolling',
'moj_spot_daily_fulfillment_under_delivered',
'moj_spot_engagement_list_garbage_backfill',
'moj_spot_hourly_overall_funnel_v2',
'moj_spot_insights_campaign_level',
'moj_spot_insights_campaign_level_base',
'moj_spot_insights_campaign_level_delete_v1',
'moj_spot_insights_campaign_level_under_delivered',
'moj_spot_insights_campaign_level_update',
'moj_spot_insights_campaign_post_engagement_rolling',
'moj_spot_insights_campaign_post_engagement_rolling_insert',
'moj_spot_insights_campaign_post_engagement_underdelivered',
'moj_spot_insights_campaign_post_engagement_underdelivered_insert',
'moj_spot_insights_campaign_post_level',
'moj_spot_insights_campaign_post_level_base_table_insert',
'moj_spot_insights_campaign_post_level_base_table_insert_multiday',
'moj_spot_insights_campaign_post_level_base_table_insert_v1',
'moj_spot_insights_campaign_post_level_base_table_update',
'moj_spot_insights_campaign_post_level_base_table_update_multiday',
'moj_spot_insights_campaign_post_level_base_table_update_v1',
'moj_spot_insights_campaign_post_level_base_underdelivered',
'moj_spot_insights_campaign_post_level_multiday',
'moj_spot_insights_campaign_post_level_v2',
'moj_spot_insights_campaign_post_level_v2_multiday',
'moj_spot_insights_campaign_post_under_delete',
'moj_spot_insights_post_level',
'moj_spot_insights_post_level_base',
'moj_spot_insights_post_level_delete',
'moj_spot_insights_post_level_delete_v1',
'moj_spot_insights_post_level_under_delivered',
'moj_spot_meta_swvp_ebyv_rolling',
'moj_spot_overall_funnel_hourly_v2',
'moj_spot_overall_funnel_video_select_flow_referrer_v1',
'moj_spot_overall_funnel_video_select_flow_referrer_v2',
'moj_spot_overall_funnel_video_select_flow_referrer_v3',
'moj_spot_overall_hourly_funnel',
'moj_spot_reactivated_user_list',
'moj_spot_recommended_1_to_5_videos',
'moj_spot_recommended_base_creator_posts',
'moj_spot_recommended_last_5_videos',
'moj_spot_recommended_video',
'moj_spot_recommended_video_history',
'moj_spot_video_recommendation_history',
'moj_spoy_ebyv_swvp',
'MOJ_static_post_metrics_agg',
'moj_udd_alerts',
'moj_user_data_deletion_status',
'moj_yesterday_top4_decile_post',
'MojBadges_16thFeb',
'MojBadgesConsolidated',
'mojlive_active_creators_notification',
'mojlivestream_inapp_dm_category_sync',
'mojlivestream_inapp_dm_chitchat_sync',
'mojlivestream_inapp_dm_gifter_sync',
'MojPremium_referrer_wise_subs_conversion',
'MojPremium_referrer_wise_subs_conversion_plus',
'monetization_opt_in_notification',
'Monthly Earning Creators New Old',
'Monthly Overall Earning Creators New Old',
'Monthly_Active_Creators',
'Monthly_Creator_Earnings',
'monthly_default_trend',
'Monthly_Earning_creator_Cuts',
'monthly_fz_ct_metrics',
'Monthly_Marketing_PU_data',
'Monthly_Marketing_PU_GMV_Contribution',
'Monthly_Marketing_PU_GMV_Contribution_from_jan23',
'Monthly_New_Old_Agency_Active_CR',
'Monthly_New_Old_Overall_Active_CR',
'monthly_new_res_retained_user_gmv',
'monthly_sc_house_edge',
'monthly_timspent_temp',
'Mserve',
'Mserve Brand on MJ',
'Mserve MJ',
'Mserve_adcat',
'Mserve_BM',
'Mserve_spends',
'mserve_todays_creative',
'Mserve_total_advertisers',
'mserve_under_over_prediction',
'mserve_under_over_prediction_today',
'MTD_Active_Creators',
'MTD_Agency_Earning_Creators_New_Old',
'MTD_Creator_Earnings',
'MTD_Earning_creator_Cuts',
'MTD_New_Old_Agency_Active_Creators',
'mtd_new_res_retained_user_gmv',
'MTD_Payout Eligible Creators_All',
'MTD_Payout Eligible Creators_without_SG',
'multi adnetwork alert on adview',
'multibrand_referrer',
'Network DRR SC',
'Network MJ',
'Network on MOJ',
'Network Placements Latest',
'',
'Network request Latest',
'',
'network_adview_user',
'Network_data',
'New_Feed_UGC_every_thirdpos',
'new_friend_zone_host_grading',
'new_friend_zone_host_grading5',
'new_live_dau',
'New_PU',
'new_rechargers_chat_live_updated',
'new_user_trending_tag',
'new_user_trending_tag_L7D',
'new_users_feed_friend_zone_host_grading1',
'new_users_feed_friend_zone_host_grading13',
'niro_1_cr_L7D',
'niro_53_Lakh_phase_offer',
'niro_53_Lakh_phase_offerL7D',
'niro_final_1cr_audiance_data',
'niro_final_1cr_audiance_data_monthly_data',
'niro_loan_funnel_1cr',
'niro_loan_funnel_phase1_offer',
'niro_loan_funnel_phase1_offer_L7D',
'niro_pn_type1',
'Non_FRND_GOLD_hosts_F2P_d0',
'NON_FRND_GOLD_hosts_F2P_D3',
'NON_FRND_GOLD_hosts_F2P_D7',
'NON_FRND_GOLD_hosts_P2P_latest_D1',
'NON_FRND_GOLD_hosts_P2P_latest_D3',
'NON_FRND_GOLD_hosts_P2P_latest_D7',
'Not Used Spot and have mints',
'notif_power_user_sa',
'OGC_Aggregators_List_preagg',
'online_offline_gmv_pus',
'Overall Admissed',
'Overall Host - earning to earning Ret',
'Overall_data',
'Overall_Host_active_to_active_Ret',
'overall_platform_users_without_overlap',
'OverConsumption_QV',
'pay now but not verified spot cohort',
'Pay now clicked but not verified 11 to 1',
'Pay now clicked but not verified 2 to 6',
'Pay now clicked but not verified 6 to 11',
'payment ini to verify 11 to 2',
'payment ini to verify 2 to 6',
'payment ini to verify 6 to 11',
'Payout Eligible Creators_All',
'Payout Eligible Creators_without_SG',
'per_vp_friends_feed_v2',
'Phone block telesign',
'pinned_posts_raw',
'pinning_data_date_x_pinning_hour',
'popularity_score_new_recharger_new',
'post_rvp98_daily_agg_v1',
'private_consultees',
'Qactive_frnd_f2p_d1',
'Qactive_frnd_hosts',
'Qactive_FRND_Hosts_F2P',
'Qactive_FRND_hosts_F2P_d3',
'Qactive_FRND_hosts_F2P_d7',
'Qactive_FRND_Hosts_free_calls',
'Qactive_FRND_hosts_P2P_latest_D1',
'Qactive_FRND_hosts_P2P_latest_D3',
'Qactive_FRND_hosts_P2P_latest_D7',
'quality_dau_new_ts _logic',
'Quota Validation 1',
'Quota Validation 2',
'ranker_slot_wise_gifting_share_Sa',
'ranker_weighted_average_scores_sa',
'rd_eow_grade',
'reactivation_tracker',
'Redash_bm_ctr_auto',
'Redash_bm_imp_auto',
'Redash_data_for_postback',
'Redash_Selfserve_Postback_schedule',
'repeat_consultee',
'reported_chatroom_abuse_score_table',
'response table for daily frontend trend',
'Response table with timeout - updated query (29-05)',
'response with timeout flag',
'responseCPM_BE_networks',
'retention_cohort_live_ranker_notifs',
'retention_friends_feed_v2',
'retention_fz_international_user',
'Riya_Moj_Notif_expdata1_layer',
'RMG_Coins_Expiry_Users_Identification',
'RO_data',
's5',
's7',
's8',
'Sanity_Moj_budgetAb_base',
'Sanity_SC_budgetAb_base',
'Sanjeev app version query sc_rn_71_code_push_adoptoin',
'SC ADS CPI Based DRR Report',
'SC BM wise DRR',
'SC BM wise imps',
'SC Content Ops New_Creators_Added',
'SC Content Ops New_Creators_Added_BucketID_Split',
'SC Content Ops Q1 2022 O1KR1 OGC_All_LangxL0',
'SC Content Ops Q1 2022 O1KR1 OGC_LangxL0',
'SC CPI Based DRR',
'SC Frontend debugging - drop between AM and response v3',
'SC frontend objects summary',
'SC FZ Ops: FZ_True_Gold_Daily_Data',
'SC FZ:',
'SC FZ: FZ_Gifters_Projections',
'sc live dau d1 retention query',
'SC Live Ops: sc_live_new_gifter',
'SC Live: SC_Live_Gifters_Projections',
'SC Live: SC_Live_Hosts_Projections',
'SC temp positionFeed',
'SC User Static Dimensions Cube - Daily Overwrite Refresh',
'sc_acquisition_all_install_d0_ho',
'sc_acquisition_day_zero_data',
'sc_acquisition_day_zero_to_two_data',
'sc_all_revenue',
'sc_audio_chatroom_daily_gifter_excl_self_gifter',
'sc_blue_l60d',
'SC_CA_l0_demo',
'SC_CA_l0_l1_demo',
'SC_CA_l0_l1_l2_demo',
'SC_CA_l0_l1_l2_lang',
'SC_CA_l0_l1_l2_state',
'SC_CA_l0_l1_l2_tier',
'SC_CA_l0_l1_lang',
'SC_CA_l0_l1_state',
'SC_CA_l0_l1_tier',
'SC_CA_l0_lang',
'SC_CA_l0_state',
'SC_CA_l0_tier',
'sc_campaign_level_arpu',
'sc_chatroom_new_gifters',
'sc_chatroom_open_7d_reinstalls',
'sc_chatroom_open_7d_reinstalls_split',
'sc_chatroom_open_last_550d',
'sc_chatroom_open_overall_reinstalls',
'sc_chatroom_open_overall_reinstalls_split',
'sc_chatroom_recharge_550d',
'sc_chatrrom_new_installs',
'sc_content_affinity',
'sc_content_ops_chatroom_dau_by_L30D_Users',
'sc_content_ops_dau_by_L30D_Users',
'sc_content_ops_l30d_ugts_by_views',
'sc_creatorid_creation_date',
'SC_DAU_Schedule',
'sc_ds_mvt_moderation_logging_table',
'sc_google_acquisition_deeper_funnel',
'sc_google_acquisition_deeper_funnel_overall',
'sc_ho',
'sc_ho_fifteen_days',
'sc_ho_session_view',
'sc_homeopen_last_500d',
'SC_IM_l0_demo',
'SC_IM_l0_lang',
'SC_IM_l0_state',
'SC_IM_l0_tier',
'SC_Inactive_Today_Automation_Posts_Maanav',
'sc_lb_genre_aggregated_prod',
'sc_lb_genre_original_prod',
'sc_lb_genre_rising_prod',
'sc_lb_lang_aggregated_prod',
'sc_lb_language_original_prod',
'sc_lb_language_rising_prod',
'sc_live_audio_slot_joiners_min_date',
'sc_live_chatroom_all_features',
'sc_live_consultation_user_first_call_details',
'sc_live_gifter_min_date',
'SC_Live_Last120d_PU',
'sc_live_min_comment_date',
'sc_live_recharge_p0_metrics',
'sc_live_user_all_features',
'sc_live_user_chatroom_cross_features',
'SC_MAU_schedule',
'sc_moj_daily_dau',
'sc_moj_demographic_data_final',
'sc_moj_hourly_dau',
'sc_mvt_nsfw_table',
'SC_new_uploads_prod_exp',
'sc_non_pii_user_table',
'sc_notif_all_issued_variant_level',
'sc_offers_new_install',
'sc_offers_reengagement',
'sc_post_boost underdelivery schedule',
'sc_post_boost_underdelivery_schedule2',
'sc_rn_70_code_push_adoptoin',
'sc_user_deactivation_table',
'sc_viewers',
'SC_Webhook_Automation_Tags',
'sclive_join_gifting_connections',
'SCN DAU',
'sco_taxonomy_distinct_lang_l0_l1_l2',
'sco_youtube_scraping_needed',
'scPF_eligibilityFunnel',
'Self serve',
'Self_serve ads DRR MJ',
'self_serve_app_postbacks_redash',
'self_serve_creative_wise_table',
'self_serve_postback',
'self_serve_postback_click',
'self_serve_revenue',
'self_serve_revenue_p',
'self_serve_whitelisted',
'selfserve_lcb_unchanged_data',
'selfsevre_all_sdk_event',
'selfsevre_all_sdk_event_today',
'selfsevre_all_sdk_event_user_info_level',
'servercost_by_sessions',
'Sharechat budgetAB Daily',
'sharechat creator score',
'sharechat_badge_post_views_language',
'sharechat_badge_post_views_language_genre',
'sharechat_creator_analytics_creator_metrics',
'sharechat_creator_analytics_post_daily_discard_eng',
'sharechat_creator_analytics_top_post',
'sharechat_creator_score_onboarding',
'sharechat_creator_score_percentile',
'sharechat_leaderboard_creator_ugc_top_genre',
'sharechat_post_daily_metrics',
'sharechat_star_badge_creators_language',
'sharechat_star_badge_creators_language_genre',
'sharechat_weekly_creator_leaderboard_genre',
'sharechat_weekly_creator_leaderboard_language',
'sharechat_weekly_creator_leaderboard_tag',
'silent_live_icon_optimisation_cohort',
'Slotwise_Lang_Audience_Gain_Dump',
'spark_ads_data',
'sparkads_campaign_view',
'spiritual_bucket_explored',
'spot app update',
'spot coupon to video select 11 to 2',
'spot inr access',
'Spot not used in Last X Days',
'spot payment drop 11 to 2',
'spot payment drop 2 to 6',
'spot payment drop 6 to 11',
'spot video to payment drop 11 to 2',
'spot video to payment drop 2 to 6',
'spot video to payment drop 6 to 11',
'spot_appv_update',
'spot_non_users_v2',
'spot_posts_self_profile_recommend_minview_swvp_ebyv',
'spot_posts_self_profile_recommend_minview_swvp_ebyv_v2',
'spot_request_automatic_refund_table',
'spot_request_moderation_total_multiple',
'spot_request_moderation_total_time_update',
'spot_request_moderation_total_v3',
'spot_request_time_updation',
'spot_rfm',
'SS DRR MJ',
'SS DRR SC',
'ss_bid_suggestions',
'ss_campaigns',
'ss_creatives',
'Sserve Brand MJ',
'SServe CPM',
'SServe MJ',
'streak_notifs_live_sa',
'SuggestedOpponents_v2',
'supply_dashboard_retention_GOLD',
'supply_dashboard_retention_NONGOLD',
'supply_performance_marketplace',
'supply_sufficient_L2s_daily_q3_2023',
'supply_sufficient_L2s_daily_wo_userbase_threshold',
'supply_sufficient_L2s_daily_wo_userbase_threshold_q2_2023',
'tagwiseboosting',
'taxonomy_notif_template_copy',
'tayna_installs_click_t1',
'tayna_installs_click_today',
'TCPA_click_cpc_query',
'TCPA_install_cpi_CI_query',
'temp_asj_db1',
'temp_asj_db2',
'temp_ttk_pricing_change_comms_20240821',
'temp_ttk_pricing_change_comms_20240821_p2p',
'temp_ttk_pricing_change_comms_20240822',
'temp_ttk_pricing_change_comms_20240823_new_react_cohort_7day',
'this_month_reward_gems',
'This_Wk_Reward_Gems',
'Timeouts Trends',
'today_reward_gems',
'Top 10 GAM Advertisers',
'Top_Agencies_MoM_Performance',
'top_post_raw',
'top_tags_data_most_shared_video_explore_redesign',
'total_follow_data_cm',
'tradedesk',
'tradeDeskBackfillQuery',
'training_data_vs_adview',
'trending_audio_post_notif',
'trends_ltto_today',
'trends_tto_views_today',
'TrendyLensMoji',
'trophy_hashtag_mints_daily',
'trophy_hashtag_mints_daily2',
'ubb_appsflyer',
'UBB_firebase',
'UGC_active_to_active_Ret',
'UGC_Chatrooms',
'ugc_cpp_daily_audience_engagement',
'ugc_cpp_daily_earning_host',
'UGC_earning_to_earning_Ret',
'ugc_funnel_data',
'ugc_host_agg_w_new_active',
'ugt_suggested_mapping',
'unfollowers_count_base_query_rolling',
'union_appography',
'update configuredcpm for TCPA sanity',
'update mfc badge',
'Used spot 0 mints',
'user_affinity_daily_v1',
'user_alldata_aggregate',
'user_completed_180d',
'user_country',
'user_custom',
'user_level_meta_views',
'user_likes',
'user-table-merge-updates-from-user-spanner-test-table',
'variable_pay_creators',
'vg_creators_active_daily',
'viral_posts',
'vishnu_trending_audios',
'Visibility_Boosting_Feed',
'visited_cr_feed',
'vp_ho_view',
'VTC Meta Final',
'vtc_dynamic_threshold',
'VTC_fields',
'yeahmobi',
'Grand Total')
GROUP BY `scheduled_query_name`,
         `refresh_schedule`
ORDER BY 1
